{{- if index .Values.tenants "ai-example" "enabled" -}}
{{- range index .Values.tenants "ai-example" "namespaces" }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  labels:
    name: {{ .name }}
    {{- if .displayName }}
    opendatahub.io/dashboard: "true"
    {{- end }}
  annotations:
    {{- if .displayName }}
    openshift.io/display-name: {{ .displayName | quote }}
    {{- end }}
    {{- if .description }}
    openshift.io/description: {{ .description | quote }}
    {{- end }}
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "10"
    helm.sh/resource-policy: keep
spec: {}
---
{{- end }}

{{- if index .Values.tenants "ai-example" "workbenches" "enabled" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ index .Values.tenants "ai-example" "workbenches" "workbench" "name" }}-storage
  namespace: {{ (index (index .Values.tenants "ai-example" "namespaces") 0).name }}
  labels:
    opendatahub.io/dashboard: "true"
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ index .Values.tenants "ai-example" "workbenches" "workbench" "storage" }}
{{- end }}
{{- end }} 